# Generated by Django 4.0.4 on 2023-02-04 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6971734d-50f5-4061-bb30-0c46cb280552'), editable=False, primary_key=True, serialize=False),
        ),
    ]
