# Generated by Django 4.0.4 on 2023-02-04 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('18abe13d-40c0-4a02-b3a9-ab2439677d23'), editable=False, primary_key=True, serialize=False),
        ),
    ]
