# Generated by Django 4.0.4 on 2023-02-04 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_todo_created_at_alter_todo_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b6a6b254-0813-4c9c-93f1-1db39490aa53'), editable=False, primary_key=True, serialize=False),
        ),
    ]
