# Generated by Django 4.1.6 on 2023-02-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_todo_todo_title_alter_todo_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
